### ISSUE TITLE
Accounting and helping hand

### ISSUE THREAD

**Issue by mjamjoum** [DoESLiverpool/covid19#32]
Hello team,

Just want to introduce myself. I am Mazen - an accountant. Tom told me about the amazing project you're working on and I thought that I'd love to help.

A few quick questions I'd like your help with (and apologies if some of these questions have been answered in other threads, just jumping in now):

1 - Do we   have any funding / how does crowd sourcing work (i.e. does it transfer to   someone's personal account, etc.) and have we gotten any funding yet? If we are only going to be transferring in £8k - £20k then a personal account may suffice.

--
2 - Who   should be authorised to do what from a disbursement stand-point (I as the   accountant can do it, but from a controls perspective should likely have   someone else I get a stamp from before anything goes out / also from audit   perspective).

--
3 - What is my expected role in fundraising? (i.e. am I involved? Or do I just manage the   money?)

--
4 - Will I be required to set-up a separate organisation (i.e. should we actually create   a not for profit for this?) - Costs like £100 if we're interested?          Otherwise we could set ourselves up as an unincorporated association in the   U.K. - in that case we don't really have to do anything, but in the case we   make a "profit", we have to pay taxes on it.

--
5 - Any   excess money, where is it going? (i.e. we state any donations above and   beyond go to X charity?

My number is also +44 7469 033 098, if anyone feels like giving me a call and wants to start trouble shooting somethings. I recently moved into recruitment and its a bit slower so happy to jump on anything you need a hand with.

Thank you,
Mazen

**Comment by afroleft** [comment]
@mjamjoum huge thank you for coming in to help us on this brother bear.

Going to work through your questions respectively based on what I know. With a bit of luck a few others will come behind me to straighten out any bits where I'm off piste. 

> 1 - Do we have any funding 

Nothing set up yet, just a few people and organisations saying they would like to donate. 

> how does crowd sourcing work (i.e. does it transfer to someone's personal account, etc.)  

Ideally we can kick open a dedicated bank account for this. Guessing for now we could operate from a personal account if needs be. 

> Who should be authorised to do what from a disbursement stand-point (I as the accountant can do it, but from a controls perspective should likely have someone else I get a stamp from before anything goes out / also from audit perspective).

Good question. Probably want a simple financial control in place. i.e. any drawdown more than £50 needs Me, Alex, Adrian sign off, for example. 

Open to other ideas. 

> 3 - What is my expected role in fundraising? (i.e. am I involved? Or do I just manage the money?)

The latter is most important, but if you can help us with the fund raising too that would be great. 

> 4 - Will I be required to set-up a separate organisation (i.e. should we actually create a not for profit for this?) - Costs like £100 if we're interested?

Guessing that makes sense otherwise we get hit by the tax office. I can spot the £100. 

> 5 - Any excess money, where is it going? (i.e. we state any donations above and beyond go to X charity?

Overspill can help us buy more materials, consumables (i.e. drill bits), equipment, pay people— some of which are freelancers—for their time.

**Comment by ajlennon** [comment]
Hi @mjamjoum - thanks for helping us out!

Couple of quick comments. I've been reaching out and have offers of financial assitance from people who are waiting to know how to send it to us.

I can't answer for the community but I can give you my thoughts.

- (1)I have been willing to accept one cheque from a friend I know personally but for the rest I need a persont to send them onto once we have a financial governance system that is clear and transparent.
- (1) DoES Liverpool is established as a CIC with a bank account so presumably there's some way to route money into that account or open another separate DoES Liverpool bank account for the purpose? Not sure about the money. I'd like to say it'll be more than 20k but I doubt it
- (2) Very good question. I don't know. My gut feeling is @amcewen  and @JackiePease  as Directors of DoES and myself. [Edit: Also @afroleft ] Others?
- (3) We need all hands to the tiller. Please jump in and help any way you can. Nobody will stop you! We are at heart a community of likeminded people and work hard to facilitate each other to help out in our own diverse ways. 
- (4) I don't _think_ so. I think DoES is enough but not sure
- (5) Yes @amcewen and I talked about this. (i) We need to state that money is for manufacture of PPE. This gives us space to pay people a living wage if this goes on a long time (as I expect it might) as well as purchasing consumables (ii) We should be clear that any money left over will be donated to the NHS PPE effort in some way.

**Comment by mjamjoum** [comment]
Great!

Thank you for all the help. I think the only thing I need right now is who to contact to get access to a DoES Liverpool bank account. Otherwise I am happy to use my own personal account (as noted below I will perform daily reconciliation to show how much money we have in and out)

As for my tasks per discussion with Tom:
1 - Create  daily reconciliations on bank account

--
2 -Set-up   purchase orders

--
3 -Create   mechanism of paying staff living wage (this will likely be the biggest struggle, but will figure it out)

--
4 - Set-up   bank account (I think we may use a personal of DoES Liverpool account if possible)

--
5 - Create   proper approval process for disbursements

--
6 - Ad-hoc

Let me know if there is anything else.

Thank you,
Mazen

**Comment by ajlennon** [comment]
Great @mjamjoum - @DoESsean handles all this for the community. Can you catch up with him to discuss? Thanks!

**Comment by DoESsean** [comment]
Hi @mjamjoum 

I've emailed DoES' accountant today to ask them about using our bank account for this, whether it's sensible to create a new entity, etc. As soon as I'd sent it, I realised we had an accountant in the repo!

I would imagine using the DoES account will be fine, but I'm not sure for certain - I guess either way it makes sense to get advice from the people that know our accounts. one thing that hadn't occurred to me till writing that email was that using the DoES account may take us over the limit where we would have to VAT register, which would have a whole host of knock on effects.

It seems like you have a handle on most everything that would need doing. The most obvious way I could help is with paying people - we could simply set them up on the DoES payroll and I could pay as part of our normal pay run. DoES is a Living Wage Employer, so that would ensure that everyone was receiving a reasonable amount for their work.

If you have any questions about how we generally work, just let me know, and I'll see if I can help.

**Comment by DoESsean** [comment]
@johnmckerrell has pointed out that, actually, it may be easier for people to invoice us and we deal with payments that way.

That does make some sense with regards to NI and tax, although depending how many hours they were doing, they may come under the thresholds anyway.

**Comment by DoESsean** [comment]
The accountant was somewhere in the region of useless - he seemed more interested in whether or not we knew about safety standards and the procedure to become an accredited NHS supplier than answering the questions I asked - his only salient points were that PPE would be VATable, and we'd have to register is our sales were over 85k for the year (that would, of course, include all DoES' sales), and that we would make a loss if we did a lot of manufacture without having an order.

**Comment by mjamjoum** [comment]
@DoESsean thanks for all this!

If you have time today would you mind giving me a call at +44(0)7469 033 098. I'm free between 2:30pm - 4:00pm U.K. time and after 5:00pm U.K time; and we can just figure a game plan of how we can best leverage accounting and divide the work.

Feel free to also text me and we can find a time from there. Looking forward to speaking!

Thank you,
Mazen

**Comment by plastictactics** [comment]
Closed on the understanding that @mjamjoum has found their feet in the accounting role (and has our gratitude for preventing any financial squabbles from bubbling up when the money runs out).
