### ISSUE TITLE
Setup a subdomain ppe.doesliverpool.com

### ISSUE THREAD

**Issue by johnmckerrell** [DoESLiverpool/covid19#34]
@johnmckerrell can do this when he knows where to point it at (from @afroleft ?)

**Comment by afroleft** [comment]
@johnmckerrell we just want a CNAME

`ppe CNAME doesppe.netlify.com.` 

<img width="816" alt="Screenshot 2020-03-31 at 19 46 27" src="https://user-images.githubusercontent.com/1761311/78063548-53fc1f80-7388-11ea-83fc-54c704b3eadf.png">

Nudge me if you get stuck 👍🏼

**Comment by johnmckerrell** [comment]
Ok, that's done. Looks like my computer cached it before I set it up (not sure how really, pre-loading the link in the email I guess) but hopefully it'll clear through before too long.

**Comment by MatthewCroughan** [comment]
@johnmckerrell It seems that the SSL is not properly configured somehow. I don't know precisely how this works, but when I redirect using CNAMEs, Cloudflare seems to handle the SSL for me as long as there is an SSL cert that is trusted by Cloudflare on the other domain, in this case netlify. Do you know how this works with whatever you're using? I viewed this fresh just a few minutes ago from my home internet connection which will not have had any caching going on.
 
Here's the cloudflare setting I'm referring to. Thanks :)

![image](https://user-images.githubusercontent.com/26458780/78068088-b9074380-738f-11ea-88f1-997b63aa6b9a.png)

**Comment by ajlennon** [comment]
Still getting the old site. Is it just my caching or ?

**Comment by MatthewCroughan** [comment]
@ajlennon If you're talking about an nginx holding page, it's probably caching on your end. Use your mobile data and an incognito browser on your phone.

**Comment by ajlennon** [comment]
No it goes to the main does page

**Comment by ajlennon** [comment]
Ah invalid certificate

![image](https://user-images.githubusercontent.com/1537834/78070146-31bbcf00-7393-11ea-8353-d1ed3da18f60.png)

**Comment by johnmckerrell** [comment]
I've setup the CNAME, SSL is a completely separate matter even if cloudfare do clever things. The SSL needs setting up at netlify which I don't have control over.

**Comment by MatthewCroughan** [comment]
Ah, I had that for some time two. My system in the makerspace still goes to the Nginx holding page. My laptop goes to the does website and my phone goes to the netlify CNAME with no SSL. 

The phone is representative of its latest state. Since that accessed the domain latest, on a separate internet connection that had not accessed that domain name.

I don't know what Nameservers are in use and what features are provided, I am only familiar with cloudflare, but there surely should be be some SSL setting in the web interface for that provider that needs to be enabled per domain. I've never understood that magic that goes on here when using DNS to redirect like this, regarding SSL, I just know that Cloudflare does that part for me. Sorry if I'm being ignorant here.

**Comment by ajlennon** [comment]
My Chrome goes straight to the "this is a dodgy site" warning as the cert is for a different domain

**Comment by MatthewCroughan** [comment]
Oh, actually, I think I understand. John is spot on, it's just going to take some time. I recall setting up a static site on Gitlab pages and it took nearly 24 hours for the certificate to sort itself out, because it's up to the remote host who's providing this hosting to manage the SSL cert for the CNAME. 

My cloudflare settings indeed did not help in this matter. Apologies for being ignorant.

**Comment by afroleft** [comment]
Taking a look this end folks. Will follow up

**Comment by afroleft** [comment]
Ok, let’s leave it until the morning and I will see if the Lets Encrypt certificate shows up. 

If not, we can get another SSL cert. 

<img width="967" alt="Screenshot 2020-03-31 at 21 25 16" src="https://user-images.githubusercontent.com/1761311/78071952-36ce4d80-7396-11ea-85c2-f11904995f62.png">

**Comment by afroleft** [comment]
SSL resolved this end 🔑

**Comment by johnmckerrell** [comment]
LGTM. Closing this now.
