### ISSUE TITLE
Can we use Sofia (small laser cutter) as well as Gerald (big laser cutter)

### ISSUE THREAD

**Issue by ajlennon** [DoESLiverpool/covid19#61]
Is this possible / sensible ?

**Comment by plastictactics** [comment]
In my experience it has taken a fair bit of time to do the drawings to maximise the number of visors per sheet - and took me a while to figure out how cut the larger source sheets (the 1020x720 white PP) into something that fits on the bed without wasting material. Another quirk of it is that we have three kinds of drawings, and two sizes of smaller sheet cut from the original full sheet, which adds a bit of complexity into cutting and tallying.

Sophia is about half the size of our bed but is wide enough for the hybrid design - so it's possible but we'll need someone to set up the drawings and test speeds (will be much slower due to the lower power). That said, it seems like something the operator could do while cutting on Gerald. If I wasn't operating ours I'd have a go - I don't think it would massively increase production but would result in extra visors so seems worth a shot.

**Comment by ajlennon** [comment]
@plastictactics the other question I have is we need to get the poly sheets cut to size to fit Sofia. Would we have to sacrifice time on Gerald to do this or could it be done with a guillotine or something. If we had to use Gerald it feels like a bit of a non-starter?

**Comment by plastictactics** [comment]
My gut feeling is that we'd get less visors out, and more complexity to process, by taking Gerald off the case just to feed Sofia, so would try doing by hand first.

We have been using a large table, spirit level and stanley knife to cut the sheet into 5 panels. It is thin, so more than doable with a steady hand (depending on your tolerances), but with the very small bed size of Sofia this would involve a lot of cuts and it gets harder to keep the edges straight as it gets smaller. Maybe if the big sheet was cut in half longways with the stanley it would fit in the guillotine for turning into bed-size sheets.

Would all take quite a lot of playing around with I expect - took me at least a day's work from the initial drawing to start laser cutting efficiently.

**Comment by ajlennon** [comment]
@plastictactics - tangential but I *do* think it's valuable to have small form factor layouts for places that might have smaller laser cutters (e.g. schools)

**Comment by Sean-anotherone** [comment]
Internals from Sophia would fit into Monty.

**Comment by amcewen** [comment]
We seem to be doing okay with just Gerald running, coupled with the other people laser-cutting locally and feeding into us for delivery
