### ISSUE TITLE
Not charging on any orders

### ISSUE THREAD

**Issue by afroleft** [DoESLiverpool/covid19#64]
A fews things feeding in to a change mind on charging where possible:

1. As we're beginning to see, the regulatory space on visors is still a bit murky. 3D Crowd now specifically setting out that they are not producing PPE. 
2. @plastictactics sent over an email a few days back highlighting where liability will    
3. @drakard Raised this BBC article [(link)](https://github.com/DoESLiverpool/covid19/issues/55#issuecomment-611837715) about charging for non [CE Marked](https://en.wikipedia.org/wiki/CE_marking) PPE is not ok 👎🏼
4. It seems people in the community were shocked at the idea that we would charge a fee to cover our costs

My personal goal all along revolved around getting as much PPE out the door as possible. Asking procurement teams—_who write £millions on invoice payables each month_—would be a sensible way to increase the size of our runway, enable us to buy extra equipment and to pay a modest living wage to those who are burning the midnight oil on this. 

But given the points set out above, I'm changing my position on this. I think we donate everything away. For sure, cash will dry up quicker, meaning the project will come to a halt faster and we might hit some difficulty paying everyone the living wage, but that's the tradeoff we're looking at.  

@JackiePease asked:
> We could do with a clear idea of how long we could sustain that for, given we have reached our stretch fundraising target.

@mjamjoum could you pull together a projection for how long we can keep the lights on? 
 
Here's the assumptions I've been working with (+ I haven't seen anyone else has raising their hands with anything different):
* Living wage for 10 people 
* ~ `£3000` for materials 
* ~ `£2000` for consumables 

Ideas welcome.

**Comment by ajlennon** [comment]
I completely agree there are concerns to be addressed here. I don't have a particular position myself on what we need to do about liability and legals.

To add into the conversation though I would make a couple of points

- I am told that because people are desperate procurement agents are putting in multiple orders all over the place then cancelling them. If we are giving away visors for free then they may well put in orders and cancel which may potentially leave us with a problem?

- If we are giving away visors does this affect our ability to "do the most good for the most people" i.e. we run out of cash. ?

**Comment by Robotorium** [comment]
I mean to your first point, I can't imagine we'll run out of places needing
visors anytime soon, can you? They might not go to the place that
originally asked for them, but there are so many places in need.

Op za 11 apr. 2020 12:24 schreef Alex Lennon <notifications@github.com>:

**Comment by mjamjoum** [comment]
Based on a back of the envelope calculation it would be 10 days of production (7k for labour, about 7k for materials based on BoM) - about 2k to spare to cover extra costs, which I hope will be enough as we have let some people take free reign. Unless we get the 50k grant. Then that’ll give us about 35 days total of runway.

Above only considering Adrienne producing. Not all the other lines of business (eg these mom and pops who are producing).

On my we need END all production that is not Adrienne’s team. We can’t cover people who are outside of the core operation or we will be out of pocket / people will be out of pocket.

Alex - I know you have a few side projects. We need to cut those, we have to stick to the main ops at DoES

On Apr 11, 2020, at 12:27 PM, Snoof <notifications@github.com> wrote:

﻿

I mean to your first point, I can't imagine we'll run out of places needing
visors anytime soon, can you? They might not go to the place that
originally asked for them, but there are so many places in need.

Op za 11 apr. 2020 12:24 schreef Alex Lennon <notifications@github.com>:

**Comment by ajlennon** [comment]
>Alex - I know you have a few side projects. We need to cut those, we have to stick to the main ops at DoES

For me the key benefit of what we're doing here is scaling the model horizontally, not limiting what we're doing to a single laser cutter at DoES

**Comment by afroleft** [comment]
> For me the key benefit of what we're doing here is scaling the model horizontally, not limiting what we're doing to a single laser cutter at DoES

Alex I think Maz might have meant we will be unable to support them financially as opposed to stopping them all together. 

Can you confirm Maz ?

**Comment by mjamjoum** [comment]
@ajlennon if we don't have money to scale, then we're dead in the water. We have 8-10 days of keeping the lights on. 

If I get a bunch of receipts and people coming to me in 10 days time saying I owe them 1k here and 3k here. And We find out we owe GBP25k, when we only have 17k in the bank - we're going to be in serious trouble and not only will we not have enough to pay people, but it will be a giant PR mess whereby we took people's money as a part of a charity and then left other people stranded.

I hope you understand that we stick to one operation unless we get another source of funding.

The big If is that if we can use the materials at DoES and the people who produce it are doing it purely on a volunteer basis, then happy days. But we will end all operations outside of DoES unless those individuals are:
1) Making the visors that Liverpool Heart and Chest Hospital has already accepted;
2) Using materials already purchased by DoES; and 
3) Doing it a volunteer basis

I hope that makes sense. We do not want a lawsuit or for us to mismanage our budget.

**Comment by amcewen** [comment]
Some thoughts, given I've been pretty quiet over here of late (thanks @Robotorium, @plastictactics, @johnmckerrell and @huffeec for chiming in with the sorts of things I'd have been saying if I'd had time).

I agree @afroleft that a switch to not-charging (not that we *have* charged anyone so far) makes sense.  That decision, that we made when we'd raised a couple of grand that I thought would help us help GPs, pharmacies, care homes, etc. who'd otherwise have missed out, got stale really quickly and I should have noticed and corrected sooner.

Looking at the £1.34/visor cost in the [bill of materials](https://github.com/DoESLiverpool/covid19/blob/master/BillOfMaterials.md#does-laser-cut-polypropylene) that'd give us enough in the gofundme for 14,000 visors.

We've also had some materials donated, and some of the costs came down with quantity ordered (although we've also got £2.5k of 3D printer filament that's not as useful as we anticipated), so the number we can actually make might be higher.

I don't think we need to worry about orders being wasted.  As @Robotorium says, there'll be plenty of demand, and @afroleft is right that the NHS has a collaborative, not capitalist, culture, and the procurement teams are already sharing their resources between each other rather than hoarding things (when I visited the Walton Centre they'd that morning received a load of goggles from Liverpool Heart and Chest Hospital, because they'd been donated loads from some local schools and shared them round).

I agree with @mjamjoum that we should focus on the existing plan of using the DoES Liverpool laser-cutters plus the ones already in the DoES Liverpool community.  That's starting to get up to speed now, but it's not humming along yet.

We should be focused on what we know how to do, not deciding to learn how to build and run a logistics company.

**Comment by afroleft** [comment]
In the interest of moving quickly — let's mark this as closed landing on a view that we are not going to charge for visors.

**Comment by mjamjoum** [comment]
Hey guys,

I'm re-opening this:

Just had a discussion with @afroleft after some shower thoughts.

Per my understanding our #1 goal is to produce as many visors as quickly as possible for the lowest cost. 

Our biggest issue is funding and our biggest cost is by far labour (GBP700+ per day). Currently we have runway for about 10 days based on current funding.

We have a few options and the key issues with each one (I'd like your thoughts @ajlennon , @amcewen @johnmckerrell @Robotorium) :

**Option 1 -** We pay people a living wage and post the 10 day period we go to a volunteer only method:

Pros:
- People get paid 

Cons:
- We only have 10 days max of runway before people begin to possibly leave
- We run out of cash in 10 days

**Option 2 -** - We have a mix of volunteers and paid individuals

Pros:
- Can keep production longer
- May be able to produce more as we have more people

Cons:
- People may get really pissed off if the guy beside them is getting paid and they're not
- Overall lowers moral because of some people getting paid and other not

**Option 3 -** We pay people 50% of living wage.   

Pros:
- We can double the run way to 20 days
- Give us more time to secure more funding
- We may be able to pay more volunteers

Cons:
- Some people may say they do not want to work unless they're getting full pay

I am a large proponent of **Option 3** - but we need to communicate it as soon as possible. It still allows people to put a bit of beans and toast on the table, and theoretically people can work for for 20 days, instead of 10 and make the same money. The way things are right now, they likely will not be getting to work before then anyway. And we get a bit more runway for additional funding.

I'd love your thoughts - and then we need to initiated ASAP if we agree on option 3 in order to manage expectations.

Thanks,
Mazen

**Comment by ajlennon** [comment]
I'm agnostic. My position is "Do the most good for the most people".

- If we run out of money and have to stop that's a bad thing.

- We'll get many many more volunteers if we pay

- I think we should minimise what is paid, and ask people to agree not to be paid if they can do, if this increases the run way. 

i.e. Looks like I'm most aligned with *Option 2 + 3 combined*

**Comment by ajlennon** [comment]
Also - we potentially have a completely different option. NHS North Wales have fully engaged with Carywn's M-Sparc operation

"NHS are doing all the logistics now (well front ending it)."

ref: https://twitter.com/M_SParc/status/1249263903323938817

If we can replicate that here we if feels like we could change the model significantly with their support.

**Comment by mjamjoum** [comment]
@ajlennon 

You seem more aligned to option 2. We have a mixed system of paying everyone a different amount or not at all. The big flaw with that is as you say "We'll get many many more volunteers if we pay", but then everyone will want to get paid. 

I honestly would volunteer my time for a pizza for a lunch. But if I find out the guy beside me is getting paid (or paid more than me) and I'm not I'd walk out right there. But that's me

**Comment by ajlennon** [comment]
>You seem more aligned to option 2. We have a mixed system of paying everyone a different amount or not at all. The big flaw with that is as you say "We'll get many many more volunteers if we pay", but then everyone will want to get paid.

Agreed. That's not my view personally (i.e. I don't want to be paid just because others are being paid) but I completely agree most people will take that view and it's a problem

**Comment by afroleft** [comment]
Off the bat, I think it's a good idea to raise this now vs. surprising people in a few days when we hit the end of the runway, so thank you Maz.

It looks to me as if there will be a few different buckets: 

1. People who are freelancers / unemployed who should benefit from the living wage
2. Those that are on a furlough scheme, meaning their income is ~80% of the way there. For these folks, we could pay ~30% of living wage as a top up. 
3. Those that are in a fortunate position to not need any income from the project.

With that, I wonder if there is an `option 4`, where we declare—either publicly, or privately—what bucket we are in.

Pay is sent out accordingly. 

Downside: 
* Runway is more difficult to project 
* More admin work figuring out who is owed what

**Comment by mjamjoum** [comment]
That makes sense a lot of sense @afroleft 

What we can do is simply - they have to declare where they sit:
A) If you are unemployed / no benefits received you get GBP 45 a day (or GBP5 an hour)
B) If Furloughed - GBP25 a day (Or GBP 3 an hour)
C) Volunteer - give the option to volunteer, 100% at the discretion of the individual.

Not a significant amount of admin as it seems we'll have only about 10 people who are producing. But I may be wrong. We can also create a wage form. We send out the wage form to each individual and they fill it out at the end of the week. They send it to a 'Line Manager', then that line manager forwards it to me with their approval and that's how we pay it out.

**Comment by afroleft** [comment]
@mjamjoum are you happy to pull together a Google Spreadsheet that we can all mark our position on?

**Comment by mjamjoum** [comment]
https://docs.google.com/spreadsheets/d/19m8ZFrqn4mDi46nKMEyoVsTl4BdYuXX8GkAJu89VxeE/edit?usp=sharing

here we go

**Comment by ajlennon** [comment]
OK what's the description of 4) ?

**Comment by drakard** [comment]
I don't know if this discussion is relevant to me, but I do not want to be paid.

**Comment by afroleft** [comment]
I don’t know what category is “I don’t need to be paid” 🤔

**Comment by drakard** [comment]
I linked some info from the government about the implications of paying people on furlough (or not on furlough) in #71 . It mostly looks good with a few caveats.

**Comment by mjamjoum** [comment]
@afroleft - kk - let's change it to - "I wish to volunteer my time"

**Comment by JackiePease** [comment]
Some people's motivation seems to be that they know how bad the situation is because they have relatives who are patients or carers in hospitals or care homes. I have been asked by 2 people if they could take a small number of visors to help their relatives - I've only been able to point them to the list. 
If we could provide them with visors, that might mean more to them than payment.

**Comment by ajlennon** [comment]
> Some people's motivation seems to be that they know how bad the situation is because they have relatives who are patients or carers in hospitals or care homes. I have been asked by 2 people if they could take a small number of visors to help their relatives - I've only been able to point them to the list.
> If we could provide them with visors, that might mean more to them than payment.

I'm doing this to help the NHS of course. But I'm also doing this to help the people I live with in my local community. I wholeheartedly agree with @JackiePease on this one.

(Not to mention that good local stories means good local news coverage which raises our exposure and hopefully gives us the opportunity to do more good work)

**Comment by afroleft** [comment]
🎵  https://www.youtube.com/watch?v=WI42hQHfbi8
