### ISSUE TITLE
Make printable stack of the DoES Verstan

### ISSUE THREAD

**Issue by SeanTomlinson30** [DoESLiverpool/covid19#84]
I am currently working on a 3D printable stack of the DoES version of the 3DVerkstan design. 

Will submit a PR once everything is sorted.

**Comment by ljphillips84** [comment]
What are you slicing in Sean? I get empty layers error and an unprintable message in PrusaSlicer for the 10 stack (haven't pressed ahead with a test yet though, so may work in spite of the error..)

Standing them up slices ok, but will presumably require a lot of support... is that the intention?

**Comment by SeanTomlinson30** [comment]
> What are you slicing in Sean? I get empty layers error and an unprintable message in PrusaSlicer for the 10 stack (haven't pressed ahead with a test yet though, so may work in spite of the error..)
> 
> Standing them up slices ok, but will presumably require a lot of support... is that the intention?


I’m using Cura. I would expect you to get an empty layer error. There is an air gap of 0.3mm between each part, it will work despite the error (assume Prusa Slicer doesn’t mangle the air gap).

The print is meant to be sliced laying flat. I’ll update the PR so it enters the slicers in the correct orientation.

**Comment by ljphillips84** [comment]
Great, thanks, will try it overnight tonight

**Comment by SeanTomlinson30** [comment]
I have since discovered that the DoES version of the Verkstan has a total vertical height which is not even divisible by 0.3. I've modified the model to be 5.4mm so that it's divisible by the desired layer height. 

I have resliced everything and will be testing that the inter-part fusion I was getting on the uppermost models is now remedied.

Will report results :)

**Comment by ljphillips84** [comment]
I found the issue was not the mask thickness (I sliced using layer heights down to 0.1 and it looked the same), but rather the gap between.

The gap had to be exactly 2x the layer height to get a solid layers on the top and bottom of all the masks. Otherwise I'd get the solid layer away from the interface (e.g. [https://www.loom.com/share/dc54609908e34110a5d335cd91096ad1](url)) Of course, a two layer gap makes the print unusable as it's printing the bottom of all stacked masks in mid-air and you get a stringy mess...

However, by adding support with an overhang angle of 90º, (7% density just about as low as I can go) I was able to get a print with each mask having a solid top and bottom, separated by a support layer. It breaks apart ok, but the support material sticks hard to the surface and makes it less easy to clean. I can get a razor blade out and trim some of it off, or even sand it, but I'm concerned that too much additional processing will create more problems than the extra through-put of the stacked method is solving...

![image](https://user-images.githubusercontent.com/10617839/79767624-7e0a8700-8321-11ea-9b6c-840b75bcf0b0.png)

**Comment by SeanTomlinson30** [comment]
The 0.3mm gap is working perfectly on my end. The issue was that because the model was not a clean multiple of the layer height, we get a drift of accuracy in the gap. Currently running a fixed version overnight. Will report back.

**Comment by ajlennon** [comment]
Hi @SeanTomlinson30 - great work! I have a Creality CR10-S working now with PETG. If you're happy with the design can I give it a go here at DoES?

**Comment by SeanTomlinson30** [comment]
Hey @ajlennon let me just update the PR with the newest version. Just exporting from Fusion (takes about 10 mins bare with me)

**Comment by SeanTomlinson30** [comment]
All updated @ajlennon

you'll just need to rotate the model when it enters the slicer. Will add that fix when I add get around to adding the Fusion files. I can make that a separate issues, though.

**Comment by ajlennon** [comment]
Wonderful thanks @SeanTomlinson30 - still trying to get into DoES and will kick off some prints :-D

**Comment by SeanTomlinson30** [comment]
PR #89 is merged, so I'll close the issue for now. Feel free to reopen as needed.
