### ISSUE TITLE
The laser cutter is being operated incorrectly or the documentation is wrong

### ISSUE THREAD

**Issue by drakard** [DoESLiverpool/covid19#85]
This page: https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/production.md#preventing-contamination-in-the-space states the power for the laser cutter should be 70.

The power indicated on the cutter LCD display during current operations is 100.

Is the documentation wrong or are we operating the cutter incorrectly (or is the displayed power incorrect)?

**Comment by ajlennon** [comment]
History:

- I set it to 100 a few days ago to speed things up
- @amcewen advised it overheats and we'll burn out the laser if we operate above 70
- we reduced power to 70 and speed. (Although Adrian advises in theory it should cut as well at 70 as at 100 - I'm not sure / don't know as when I was testing somebody had knocked the laser out of focus while cleaning)
- somebody has been in since and optimised it again and we're back up at 90-100

We need to follow @amcewen 's advice arrive at a design within safe machine tolerance and stop changing things (imvho)

**Comment by drakard** [comment]
@ajlennon Does that mean it should now be set to 70? It would be great to know what the immediate term / temporary operating expectation is. Or if I should determine that myself in some way. Until other instruction I will leave the settings as they are when I arrive.

**Comment by ajlennon** [comment]
Only @amcewen knows...

**Comment by huffeec** [comment]
The power setting showing on the LCD screen of the controller board is independent of the settings in the Lasercut software. It's fine showing 100
The power setting in Lasercut shouldn't be over 70. From the pictures i saw on Google they look like reasonable settings. I've not been using this machine so others are probably best to advise but they should work fine.

**Comment by amcewen** [comment]
Everyone who has been through the laser-cutter induction will have been told the maximum power setting for Gerald is 70.  (For Sophia it's 50).  The rules of the laser-cutter induction apply at all times, even during pandemics ;-)

**Comment by drakard** [comment]
I have updated the page https://github.com/DoESLiverpool/covid19/blob/master/visor-designs/laser-cut/production.md Could someone who is more familiar with the machine please confirm what I have written is correct. If so we can close this issue.

**Comment by huffeec** [comment]
Looks good to me.
