### ISSUE TITLE
Hygiene plan for produced units

### ISSUE THREAD

**Issue by MatthewCroughan** [DoESLiverpool/covid19#9]
@RussCoty mentioned in https://github.com/DoESLiverpool/somebody-should/issues/1415#issuecomment-605068583:

> Not sure if I’ve missed anything here but is there a plan for hygiene in place during production?
> 
> Presumably that would have to be adressed before they could be used.

**Comment by MatthewCroughan** [comment]
At least for the 3D Printed units, this seems simple. If the parts are being produced automatically, they can simply drop into a well protected and disinfected parts bin which has little to no human interaction. The visor polypropylene can then be cut and hole punched separately from this, that then means that there is less risk of the whole assembly being compromised.

**Comment by magman2112** [comment]
Ok, let’s think of some basics.

People assembling any units should be wearing disposable gloves as a minimum and ideally face masks as well, but the last item is a bit ironic as these have been in short supply for the NHS anyway. Hand washing before gloving is another good step.

Cleaning of surfaces used for assembly would be a required step, possibly use the event room to separate manufacture from assembly. So Is having the right cleaning products and likely documenting the process steps used.

Do we need to clean any of the components before assembly?

Can we possibly use UV lamps to sterilise completed units? Possibly quite good for the visors as they are transparent, but how long would they need to be exposed? Might be a good step after assembly is completed and prior to packaging.

**Comment by ajlennon** [comment]
@magman2112 @MatthewCroughan 

This is the standard operating procedure from the covid-19volunteersuk.slack.com group

[3d crowd - Standard Operating Procedures_V1.0.pdf](https://github.com/DoESLiverpool/covid19/files/4395078/3d.crowd.-.Standard.Operating.Procedures_V1.0.pdf)

**Comment by afroleft** [comment]
Worth noting this UCLA study that shows Covid 19 lives for 3 days on plastics. [Link](https://www.sciencedaily.com/releases/2020/03/200320192755.htm)

Shooting from the hip, but could just we add 3 days stow to the dispatch workflow?

**Comment by ajlennon** [comment]
Can we get somebody in from LU or LJMU to comment on this?

**Comment by mdunschen** [comment]
Have you checked with the recipients? Hospitals have ways to sterilise
stuff, maybe they run it through a steriliser process anyway.

I admire all your enthusiasm and applaude your efforts and ingenuity. Well
done all round, I wish I could help in any way.

Martin

**Comment by ajlennon** [comment]
Dan over at Sensor City (I think) was saying we can't sterilize PLA. 

His suggestion was we use PETG as it's similarly priced, similar availability and can be sterilized.

There are some question marks over how easy it is to print PETG with what we have versus PLA

**Comment by JackiePease** [comment]
I think in most cases it needs to be clean rather than sterile - certainly PLA is in use in this country and elsewhere. and I do have more information about cleaning etc. that I'm going to add tomorrow morning. PET G does seem to have some advantages though, if easy to print.
________________________________

**Comment by JackiePease** [comment]
Here's a link to cleaning guidelines from a Spanish site 'Maker Community of the Basque Country against Coronavirus'  which involves more work than some of the others (there are also other 3dp designs on the same page).

https://covideuskadi.net/impresion-3d/

2 - DISINFECTION AND PACKAGING OF MATERIAL

THIS PROCESS MUST BE PERFORMED WITH GLOVES AND MASK.

Important, take your temperature before starting and in case you exceed 37.2 degrees or have symptoms of having the virus, please do not hand over your material as it can infect other people.

1 - Cleaning of the material, with soap and water
2 - Disinfection with any of the materials listed in the protocol (sanitol is worth, the bleach mixture at 30ml per liter of water is worth)
3 - From this point on, you should avoid touching the pieces with your hands. Ideally, you should wear gloves, but if you don't have them, you can use another garbage bag and that your hands are in contact with the outside and the pieces with the inside.
4 - Dry the pieces so that there are no traces of moisture, actively using kitchen paper or air outside. Inside it is not advisable since the particles that we expel when speaking can be deposited and the previous disinfection work would not do any good.
5 - Put the materials in a bag using gloves (do not touch the parts or the bag with your hands) and close the bag. If you do not have hermetic ZIP-type bags, you can use garbage bags.
6 - Put the bags with pieces in a second bag using gloves. Once closed, that second bag will not be considered clean and disinfected in transport.
7 - Somehow mark the number of pieces that go into the bag, with a marker.

We understand that all the indicated requirements may not be available, but please try to carry out this process in the best possible way (without sneezing over the pieces before putting them in the bag, etc.)
IMPORTANT! The solution is ONLY effective for 24 hours.

**Comment by JackiePease** [comment]
Here's Prusa's advice on sterilising (appears to be mainly for end users):
https://help.prusa3d.com/en/article/prusa-face-shield-disinfection_125457#_ga=2.40241318.506614383.1585404591-848980217.1585404591

**Comment by seanmtracey** [comment]
Hey everyone, has anybody thought about constructing a UV light chamber to store these masks in? I don’t know what effect UV light has on viruses, but IIRC it can eradicate bacteria. Maybe it’s something we can put together to extend the shelf life of each mask?

**Comment by ajlennon** [comment]
Hey @Sean-anotherone - I think you were looking at my UV chamber (loads of little UV lights on a strip) and we were thinking it didn't really work that well. You were talking about what we'd need to do to make a "proper" one. What do you think of @seanmtracey 's idea about using it for sanitisation?

**Comment by Sean-anotherone** [comment]
Hi, If I recall correctly, to effectively sterilise you need "hard" UV - around 254 nm, I think that is the principal line from a LP mercury lamp, LEDS are mostly barely below 400nm, so not particularly effective.  The intensity (rate of energy deposition) needs to be up there in the J cm-2 range too, again, tricky for many LEDs, particularly the off the shelf ones.
This might do it...
US $2.89 35% OFF|Işıklar ve Aydınlatma'ten Ultraviyole Lambalar'de 275nm UVC LED modülü DIY için UVC dezenfeksiyon lambaları USB güç kaynağı kurulu derin UVC LED mor işık sterilizasyon 285nm AliExpress'da

| 
| 
| 
|  |  |

 |

 |
| 
|  | 
US $2.89 35% OFF|Işıklar ve Aydınlatma'ten Ultraviyole Lambalar'de 275nm...

Smarter Shopping, Better Living! Aliexpress.com
 |

 |

 |





Sean

    On Sunday, 29 March 2020, 13:46:49 BST, Alex Lennon <notifications@github.com> wrote:  
 
 


Hey @Sean-anotherone - I think you were looking at my UV chamber (loads of little UV lights on a strip) and we were thinking it didn't really work that well. You were talking about what we'd need to do to make a "proper" one. What do you think of @seanmtracey 's idea about using it for sanitisation?

**Comment by amcewen** [comment]
Spoke to a procurement manager at a local hospital just now, and he thinks they'd be likely to wipe them down with sterilising wipes they have when they come to use them, so there'd be some level of processing at their end.  (And at the moment they're using masks that are four years out of date, and wiping down goggles...)

Irene, our cleaner, recommended [hibiscrub](https://www.thevetstore.net/shop/hibiscrub-5-litre/) for cleaning down the space (and possibly items before we send them out).  You dilute it down 20:1 or something, so it'll go a long way.  I'll add it to #21.

**Comment by epsaul** [comment]
UVC is used to sterilse but suggest you outsource this rather than try to build one as UVC is pretty dangerous. Hospitals or University laboratories will have something like this: https://www.finsentech.com/nanoclave-cabinet

**Comment by ajlennon** [comment]
Via 3DCrowd on Prusa Sterlization

[https://help.prusa3d.com/en/article/prusa-face-shield-disinfection_125457](https://help.prusa3d.com/en/article/prusa-face-shield-disinfection_125457)

**Comment by ajlennon** [comment]
Heard a very interesting comment from 3DCrowd coordinators today @huffeec 

>A lot of us are sanitising PPE with isopropyl alcohol. The feedback was that 99% was less effective than watered down 60% for reasons that are too complicate for me involving cell structures and so forth. Perhaps worth noting
